require_relative './corto/infrastructure/container.rb'
require_relative './corto/adapters/repositories/url.rb'
require_relative './corto/infrastructure/db/url/in_memory.rb'
require_relative './corto/use_cases/url/shortener.rb'
require_relative './corto/entities/url.rb'
